version: '2'

services:
  minecraft:
    image: itzg/minecraft-server:latest
    ports:
      - '25565:25565'
    restart: on-failure
    environment:
      - EULA=TRUE
      - VERSION=1.19
      - USE_LARGE_PAGES=true
      - VIEW_DISTANCE=16
      - MEMORY=16G
      - DIFFICULTY=hard
    volumes:
      - ./.data:/data
