version: '2'

services:
  minecraft:
    image: itzg/minecraft-server
    ports:
      - '25565:25565'
    restart: on-failure
    environment:
      - EULA=TRUE
      - VERSION=SNAPSHOT
      - USE_LARGE_PAGES=true
      - VIEW_DISTANCE=16
      - MEMORY=16G

      # Caves and Cliffs data pack
      - 'RESOURCE_PACK=https\://launcher.mojang.com/v1/objects/643b1f8f7f71c74ffc913e8572f52fd5bca88282/CavesAndCliffsPreview.zip'
    volumes:
      - ./.data:/data
